spring:
  profiles:
    active: "local"
  main:
    banner-mode: "off"

server:
  email: techgem1986@gmail.com
management:
  security:
    enabled: false
---

spring:
  profiles: local

---

spring:
  profiles: aws
