# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Building Jar
          command: mvn -B -DskipTests clean package
      - run:
          name: Running JUnit
          command: mvn test
      - run:
          name: Sonar Analysis
          command: mvn verify sonar:sonar -Dsonar.projectKey=techgem1986_tma-crud-service
      - run:
          name: Docker Login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Building Container Image
          command: mvn clean compile jib:build -Dimage=techgem1986/tma-crud-service:$CIRCLE_BUILD_NUM
workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
