package com.techgem.tma.model;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@DynamoDBTable(tableName = "tasks")
public class Task {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String taskId;
    @DynamoDBAttribute
    private String taskDescription;
    @DynamoDBAttribute
    private String scheduledDate;
    @DynamoDBAttribute
    private String status;
    @DynamoDBAttribute
    private String reminder;


}
